// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfxepmvheviirsbbfgvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmeGVwbXZoZXZpaXJzYmJmZ3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTM5MDcsImV4cCI6MjA1OTc4OTkwN30.K-1rWJ6FsOVCbjaAzl06jKM8lLSB8AG2Kvi9VaRzKVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);